name: FarmProtect
version: '${project.version}'
main: com.jjkay03.farmprotect.FarmProtect
api-version: '1.21'

author: "jjkay03"
website: https://modrinth.com/project/farmprotect
description: "Protect your farmland from being trampled."

